In [223]:
import pandas as pd
import numpy as np

In [224]:
# Realizo a leitura da planilha. Uso a Engine OpenPyxl para transformar o xlsx em Dataframe
df = pd.read_excel("./Planilha todas as cidade ESAVI.xlsx", engine="openpyxl")

df.info

<bound method DataFrame.info of     Município de vacinação  Idade Evento  Data da Notificação Raça/Cor  \
0                Abadiânia          18.0  2022-02-16 00:00:00   Branca
1                Abadiânia          18.0  2022-02-16 00:00:00    Parda
2                Abadiânia          18.0  2022-02-16 00:00:00    Parda
3                Abadiânia          18.0  2022-02-16 00:00:00   Branca
4                Abadiânia          18.0  2022-02-16 00:00:00   Branca
..                     ...           ...                  ...      ...
447   Terezópolis de Goiás           3.0                 2021    Parda
448   Terezópolis de Goiás           4.0                 2021    Parda
449   Terezópolis de Goiás          40.0                 2021   Branca
450   Terezópolis de Goiás          52.0                 2021    Parda
451   Terezópolis de Goiás          44.0                 2021    Preta

          Sexo                            Imunobiológico (vacina)  \
0    Masculino                            1: Astrazeneca/Fiocruz
1    Masculino                            1: Astrazeneca/Fiocruz
2     Feminino                            1: Astrazeneca/Fiocruz
3     Feminino                            1: Astrazeneca/Fiocruz
4     Feminino                            1: Astrazeneca/Fiocruz
..         ...                                                ...
447  Masculino                                1:Pfizer Pediatrica
448   Feminino                                1:Pfizer Pediatrica
449  Masculino  1: Astrazeneca/Fiocruz / 2: Astrazeneca/Fiocru...
450  Masculino  1:Pfizer/ 2: Astrazeneca/Fiocruz / 3: Astrazen...
451  Masculino  1: Astrazeneca/Fiocruz / 2: Astrazeneca/Fiocru...

                                                  Dose Gestante  \
0                                          1:  1ª Dose      Não
1                 1: 1ª Dose / 2: 2ª Dose / 3: 3ª dose      Não
2                           1: 1ª Dose / 2: -  2ª Dose      Não
3                              1: 1ª Dose / 2: 2ª Dose      Não
4                                          1:  1ª Dose      Não
..                                                 ...      ...
447                                        1:  1ª Dose      Não
448                                        1:  1ª Dose      Não
449  1: 1ª Dose / 2: 2ª Dose / 3: 3ª Dose / 4: 4ª D...      Não
450  1: 1ª Dose / 2: 2ª Dose / 3: 3ª Dose / 4: 4ª Dose      Não
451  1: 1ª Dose / 2: 2ª Dose / 3: 3ª Dose / 4: 4ª Dose      Não

     Mês de gestação Mulher amamentando no momento da vacinação?  \
0                0.0                                         Não
1                0.0                                         Não
2                0.0                                         Não
3                0.0                                         Não
4                0.0                                         Não
..               ...                                         ...
447              0.0                                        Não
448              0.0                                         Não
449              0.0                                        Não
450              0.0                                        Não
451              0.0                                        Não

            Tipo de Evento Reação / evento adverso Classificação de gravidade  \
0    1: Erro de Imunização     1: Dose inadequada                1: Não grave
1    1: Erro de Imunização     1: Dose inadequada                1: Não grave
2    1: Erro de Imunização     1: Dose inadequada                1: Não grave
3    1: Erro de Imunização     1: Dose inadequada                1: Não grave
4    1: Erro de Imunização     1: Dose inadequada                1: Não grave
..                     ...                     ...                        ...
447  1: Erro de Imunização                     NaN               1: Não grave
448  1: Erro de Imunização                     NaN               1: Não grave
449  1: Erro de Imunização                     NaN               1: Não grave
450  1: Erro de Imunização                     NaN               1: Não grave
451  1: Erro de Imunização                     NaN                        NaN

    Gravidade Desfecho (evolução do caso)  \
0           0        1: Cura sem sequelas
1           0        1: Cura sem sequelas
2           0        1: Cura sem sequelas
3           0        1: Cura sem sequelas
4           0        1: Cura sem sequelas
..        ...                         ...
447         0                           0
448         0                           0
449         0                           0
450         0                           0
451         0                           0

                        Doenças (CID10) - Preexistente  \
0                                                    0
1                                                    0
2                                                    0
3                                                    0
4                                                    0
..                                                 ...
447                                                  0
448                                                  0
449  1: Z258 - Necessidade de imunização contra out...
450  1: Z258 - Necessidade de imunização contra out...
451  1: Z258 - Necessidade de imunização contra out...

    Medicamento em uso anterior ou durante a vacinação Nome do Medicamento  \
0                                                  Não                 Não
1                                                  Não                 Não
2                                                  Não                 Não
3                                                  Não                 Não
4                                                  Não                 Não
..                                                 ...                 ...
447                                                Não                 Não
448                                                Não                 Não
449                                                Não                 Não
450                                                Não                 Não
451                                                Não                 Não

    Houve atendimento médico? Tipo de Atendimento
0                         Não                   0
1                         Não                   0
2                         Não                   0
3                         Não                   0
4                         Não                   0
..                        ...                 ...
447                       Não                   0
448                       Não                   0
449                       Não                   0
450                       Não                   0
451                       Não                   0

[452 rows x 20 columns]>

In [225]:
df.describe()

       Idade Evento  Mês de gestação
count    444.000000       444.000000
mean      36.081081         0.126126
std       21.162762         1.778310
min        0.000000         0.000000
25%       18.000000         0.000000
50%       35.000000         0.000000
75%       51.000000         0.000000
max       90.000000        35.000000

In [226]:
df = df.dropna()

print (df.isna().sum()) # Aqui consigo descobrir se eliminei todos os registros NaN presentes na planilha

Município de vacinação                                0
Idade Evento                                          0
Data da Notificação                                   0
Raça/Cor                                              0
Sexo                                                  0
Imunobiológico (vacina)                               0
Dose                                                  0
Gestante                                              0
Mês de gestação                                       0
Mulher amamentando no momento da vacinação?           0
Tipo de Evento                                        0
Reação / evento adverso                               0
Classificação de gravidade                            0
Gravidade                                             0
Desfecho (evolução do caso)                           0
Doenças (CID10) - Preexistente                        0
Medicamento em uso anterior ou durante a vacinação    0
Nome do Medicamento                                   0
Houve atendimento médico?                             0
Tipo de Atendimento                                   0
dtype: int64

In [227]:
df['Dose'] = df['Dose'].str.findall(r'[1-6]') 
# Encontra os valores pelo regex (os valores encontrados de 1-6, e 'divindo' pelos números)

df['Dose'] = df['Dose'].apply(lambda x: list(dict.fromkeys(x)))
# Apply é uma função do Pandas que a gente pode utilizar para colocar uma função a ser resolvida em cada linha
# Lambda é só uma forma de definir uma função, de forma curta
# No final, ele gera um dicionário pelo número (portanto, pode apenas existir uma chave)

df_split = pd.DataFrame(df['Dose'].tolist(), index=df.index)
# To list transforma esse dicionário especificamente em uma lista ['1,2,3']

stacked = df_split.stack()
# Ele gera uma pilha de valores em lista, mantendo ordem pelo índice original

dummies = pd.get_dummies(stacked)
# Ele gera os dummies ()

dummies = dummies.groupby(level=0).max()

dummies = dummies.rename(columns={
    '1': 'Tomou_Primeira_Dose',
    '2': 'Tomou_Segunda_Dose',
    '3': 'Tomou_Terceira_Dose',
    '4': 'Tomou_Quarta_Dose',
    '5': 'Tomou_Quinta_Dose',
    '6': 'Tomou_Sexta_Dose'
})

df = pd.concat([df, dummies], axis=1)

df = df.drop(columns='Dose')

In [228]:

df_split = (
    df['Imunobiológico (vacina)']
    .str.replace(r'^\d+:\s*', '', regex=True)
    .str.split(r'/\s*\d+:', expand=True, regex=True)
)
# Utilizo o regex para splitar em colunas as marcas
#Além disso, retiro os valores "1:/2:"

df_split = df_split.rename(columns={
    0: 'Marca_Primeira_Dose',
    1: 'Marca_Segunda_Dose',
    2: 'Marca_Terceira_Dose',
    3: 'Marca_Quarta_Dose',
    4: 'Marca_Quinta_Dose',
    5: 'Marca_Sexta_Dose'
    })
#

df = pd.concat([df, df_split], axis=1)

df = df.drop(columns='Imunobiológico (vacina)')

df.head(3)

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Reação / evento adverso,...,Tomou_Terceira_Dose,Tomou_Quarta_Dose,Tomou_Quinta_Dose,Tomou_Sexta_Dose,Marca_Primeira_Dose,Marca_Segunda_Dose,Marca_Terceira_Dose,Marca_Quarta_Dose,Marca_Quinta_Dose,Marca_Sexta_Dose
0,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Masculino,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,...,False,False,False,False,Astrazeneca/Fiocruz,NaN,NaN,NaN,NaN,NaN
1,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Masculino,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,...,True,False,False,False,Astrazeneca/Fiocruz,NaN,NaN,NaN,NaN,NaN
2,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Feminino,Não,0.0,Não,1: Erro de Imunização,1: Dose inadequada,...,False,False,False,False,Astrazeneca/Fiocruz,NaN,NaN,NaN,NaN,NaN

In [229]:
df_limpo = df['Reação / evento adverso'].replace(' ','').str.replace(r'[\d+:\s*]', '', regex=True).str.split('/',regex=True, expand=True)

stacked = df_limpo.stack()
dummies = pd.get_dummies(stacked)


dummies.head(20)

df = pd.concat([df, dummies], axis=1)
df = df.drop(columns='Reação / evento adverso')

df.head(5)

,Município de vacinação,Idade Evento,Data da Notificação,Raça/Cor,Sexo,Gestante,Mês de gestação,Mulher amamentando no momento da vacinação?,Tipo de Evento,Classificação de gravidade,...,Síndromegripal,Taquicardia,Tosse,Trombose,Urticáriageneralizada,Vacinaincorreta,Vacinaparaidadeinadequada,Vacinavencida,Vomito,Vômito
0,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Masculino,Não,0.0,Não,1: Erro de Imunização,1: Não grave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Masculino,Não,0.0,Não,1: Erro de Imunização,1: Não grave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abadiânia,18.0,2022-02-16 00:00:00,Parda,Feminino,Não,0.0,Não,1: Erro de Imunização,1: Não grave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Feminino,Não,0.0,Não,1: Erro de Imunização,1: Não grave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abadiânia,18.0,2022-02-16 00:00:00,Branca,Feminino,Não,0.0,Não,1: Erro de Imunização,1: Não grave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN